const translations = {
    en: {
        inferModelConfig:'Model Config',
        inferModel:'Model:',
        inferTileSize:'Tile Size:',
        inferScale:'Scale:',
        inferSkipAlpha:'SkipAlpha:',
        inferResizeTo:'Resize To:',
        inferProcessImage:'Process Image',
        inferInputImage:'Input Image:',
        inferInputFolder:'Input Folder:',
        inferSaveTo:'Save To:',
        inferProgress:'Progress:',
        inferBatchProcess:'Batch Process:',
        inferSelectButton:'Select',
        inferStartButton:'Start',
        inferAlertFinish:'Your image has been processed.',
        inferAlertError:'An error occurred while processing your image.',
        inferAlertMissingParam:'Missing required parameters (model or inputs and outputs)',
    },
    zh: {
        inferModelConfig:'模型配置',
        inferModel:'模型:',
        inferTileSize:'分块大小:',
        inferScale:'放大倍率:',
        inferSkipAlpha:'跳过透明通道:',
        inferResizeTo:'缩放为:',
        inferProcessImage:'处理图片',
        inferInputImage:'待处理图片:',
        inferInputFolder:'待处理文件夹:',
        inferSaveTo:'保存位置:',
        inferProgress:'处理进度:',
        inferBatchProcess:'批量处理:',
        inferSelectButton:'选 择',
        inferStartButton:'开始处理',
        inferAlertFinish:'图片已处理完成',
        inferAlertError:'处理发生了错误',
        inferAlertMissingParam:'缺少必填参数(模型/待处理图片/保存位置)',
    },
};

export default translations;
